name: CI

on:
  push:
  pull_request_target:

permissions:
  contents: read
  packages: write

env:
  DOCKER_DRIVER: overlay2
  FAST_MODE: false

jobs:
  build-image:
    name: Build Image
    runs-on: ubuntu-22.04
    outputs:
      image-tag: ${{ steps.prepare.outputs.image-tag }}
      repo-name: ${{ steps.prepare.outputs.repo-name }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Prepare
        id: prepare
        run: |
          BRANCH_NAME=$(echo "${GITHUB_REF##*/}" | tr '[:upper:]' '[:lower:]')
          REPO_NAME=$(echo "${{ github.repository }}" | tr '[:upper:]' '[:lower:]')
          echo "image-tag=${BRANCH_NAME}" >> $GITHUB_OUTPUT
          echo "repo-name=${REPO_NAME}" >> $GITHUB_OUTPUT

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: ./contrib/containers/ci
          file: ./contrib/containers/ci/Dockerfile
          push: true
          tags: |
            ghcr.io/${{ steps.prepare.outputs.repo-name }}/deccordcore-ci-runner:${{ steps.prepare.outputs.image-tag }}
            ghcr.io/${{ steps.prepare.outputs.repo-name }}/deccordcore-ci-runner:latest
          cache-from: type=registry,ref=ghcr.io/${{ steps.prepare.outputs.repo-name }}/deccordcore-ci-runner:latest
          cache-to: type=inline

  build-depends:
    name: Build Dependencies
    needs: build-image
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        include:
        - build_target: arm-linux
          host: arm-linux-gnueabihf
        - build_target: linux64
          host: x86_64-pc-linux-gnu

    container:
      image: ghcr.io/${{ needs.build-image.outputs.repo-name }}/deccordcore-ci-runner:${{ needs.build-image.outputs.image-tag }}
      options: --user root

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          
      - name: Fix permissions
        run: |
          chmod +x depends/config.guess
          chmod +x depends/config.sub
          chmod +x depends/gen_id
          chmod +x depends/builders/*.mk
          chmod -R 755 depends

      - name: Cache depends sources
        uses: actions/cache@v4
        with:
          path: |
            depends/sources
          key: depends-sources-${{ hashFiles('depends/packages/*') }}
          restore-keys: |
            depends-sources-

      - name: Cache depends
        uses: actions/cache@v4
        with:
          path: |
            depends/built
            depends/${{ matrix.host }}
          key: ${{ runner.os }}-depends-${{ matrix.build_target }}-${{ hashFiles('depends/packages/*') }}
          restore-keys: |
            ${{ runner.os }}-depends-${{ matrix.build_target }}-${{ hashFiles('depends/packages/*') }}
            ${{ runner.os }}-depends-${{ matrix.build_target }}

      - name: Build depends
        run: |
          mkdir -p depends/builders
          make -j$(nproc) -C depends HOST=${{ matrix.host }}

  build:
    name: Build
    needs: [build-image, build-depends]
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        include:
          - build_target: arm-linux
            host: arm-linux-gnueabihf
            depends_on: arm-linux
          - build_target: linux64
            host: x86_64-pc-linux-gnu
            depends_on: linux64
          - build_target: linux64_cxx20
            host: x86_64-pc-linux-gnu
            depends_on: linux64
          - build_target: linux64_fuzz
            host: x86_64-pc-linux-gnu
            depends_on: linux64
          - build_target: linux64_nowallet
            host: x86_64-pc-linux-gnu
            depends_on: linux64
          - build_target: linux64_sqlite
            host: x86_64-pc-linux-gnu
            depends_on: linux64
          - build_target: linux64_tsan
            host: x86_64-pc-linux-gnu
            depends_on: linux64
          - build_target: linux64_ubsan
            host: x86_64-pc-linux-gnu
            depends_on: linux64

    container:
      image: ghcr.io/${{ needs.build-image.outputs.repo-name }}/deccordcore-ci-runner:${{ needs.build-image.outputs.image-tag }}
      options: --user root

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0

      - name: Fix permissions
        run: |
          chmod -R 777 .
          # Specifically ensure build scripts are executable
          chmod +x ci/test/00_setup_env.sh
          chmod +x ci/deccord/*.sh
          chmod +x depends/config.guess
          chmod +x depends/config.sub
          find . -name "*.sh" -exec chmod +x {} \;

      - name: Restore depends cache
        uses: actions/cache/restore@v4
        with:
          path: |
            depends/built
            depends/${{ matrix.host }}
          key: ${{ runner.os }}-depends-${{ matrix.depends_on }}-${{ hashFiles('depends/packages/*') }}

      - name: Determine PR Base SHA
        id: vars
        run: |
          echo "PR_BASE_SHA=${{ github.event.pull_request.base.sha || '' }}" >> $GITHUB_OUTPUT

      - name: CCache
        uses: actions/cache@v4
        with:
          path: |
            /cache
          key: ${{ runner.os }}-${{ matrix.build_target }}-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.build_target }}-${{ github.sha }}
            ${{ runner.os }}-${{ matrix.build_target }}-${{ steps.vars.outputs.PR_BASE_SHA }}
            ${{ runner.os }}-${{ matrix.build_target }}

      - name: Build source and run tests
        run: |
          git config --global --add advice.detachedHead false
          git config --global --add safe.directory "$PWD"
          GIT_HEAD="$(git rev-parse HEAD)"
          # Skip develop branch checkout
          # git checkout develop
          git checkout ${GIT_HEAD}
          
          # Setup build environment
          CCACHE_SIZE="400M"
          CACHE_DIR="/cache"
          mkdir -p /output
          BASE_OUTDIR="/output"
          BUILD_TARGET="${{ matrix.build_target }}"
          
          # Install build dependencies
          apt-get update
          apt-get install -y build-essential libtool autotools-dev automake pkg-config bsdmainutils python3 \
            make build-essential libssl-dev zlib1g-dev libbz2-dev libreadline-dev libsqlite3-dev \
            wget curl llvm libncursesw5-dev xz-utils tk-dev libxml2-dev libxmlsec1-dev libffi-dev liblzma-dev
          
          # Install pyenv and Python 3.8.16
          curl https://pyenv.run | bash
          export PATH="$HOME/.pyenv/bin:$PATH"
          eval "$(pyenv init -)"
          eval "$(pyenv virtualenv-init -)"
          pyenv install 3.8.16
          pyenv global 3.8.16
          
          # Show system information
          uname -a
          gcc --version
          python --version
          
          # Run autogen and configure with verbose output
          ./autogen.sh
          cd build-ci
          ../configure --enable-debug --disable-dependency-tracking \
            --prefix=$DEPENDS_DIR/$HOST \
            --bindir=$BASE_OUTDIR/bin \
            --libdir=$BASE_OUTDIR/lib \
            --with-utils \
            --with-libs \
            --with-daemon \
            --enable-debug \
            V=1 || (cat config.log && false)
          
          # Build source
          source ./ci/deccord/matrix.sh
          ./ci/deccord/build_src.sh
          ./ci/deccord/test_unittests.sh
        env:
          DOCKER_DRIVER: overlay2
          FAST_MODE: false
          HOST: ${{ matrix.host }}
          DEPENDS_DIR: /depends
          CC: gcc
          CXX: g++
          PYENV_ROOT: "$HOME/.pyenv"
          PATH: "$PYENV_ROOT/bin:$PATH"
        shell: bash

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts-${{ matrix.build_target }}
          path: |
            /output
